cycles_delay: 60

kafka:
  bootstrap_servers: kafka:9092
  auto_offset_reset: earliest
  enable_auto_commit: false
  group_id: etl_service

clickhouse:
  host: clickhouse
  port: 8123

tasks:
  - task_name: Registration of viewing messages
    num_messages: 100000
    data_class: !!python/name:etl_tasks.movie_watch.data_structures.MovieWatch
    kafka:
      topics:
        - movie_watches
    clickhouse:
      table: movie_watches
      table_ddl: "etl_tasks/movie_watch/table.sql"
